import {
  Combine,
  Scissors,
  RotateCw,
  FileX2,
  Hash,
  Sticker,
  FileImage,
  Images,
  FileText,
  Layers,
  Minimize2,
  Info,
} from 'lucide-react';
import type { Tool } from './types';

export const TOOLS: Tool[] = [
  {
    id: 'merge',
    name: 'Merge PDF',
    short: 'Combine PDFs',
    description: 'Combine multiple PDF files into one document in the order you choose.',
    icon: Combine,
    category: 'organize',
    accent: 'sky',
    multiple: true,
  },
  {
    id: 'split',
    name: 'Split PDF',
    short: 'Extract ranges',
    description: 'Extract a page range into a new PDF, or split into individual pages.',
    icon: Scissors,
    category: 'organize',
    accent: 'teal',
  },
  {
    id: 'reorder',
    name: 'Reorder Pages',
    short: 'Drag & drop pages',
    description: 'Visually rearrange, rotate, and delete pages from your PDF.',
    icon: Layers,
    category: 'organize',
    accent: 'violet',
  },
  {
    id: 'delete-pages',
    name: 'Delete Pages',
    short: 'Remove pages',
    description: 'Remove the pages you do not need and keep the rest.',
    icon: FileX2,
    category: 'organize',
    accent: 'rose',
  },
  {
    id: 'rotate',
    name: 'Rotate PDF',
    short: 'Rotate pages',
    description: 'Rotate all pages of a PDF by 90°, 180°, or 270°.',
    icon: RotateCw,
    category: 'edit',
    accent: 'amber',
  },
  {
    id: 'page-numbers',
    name: 'Page Numbers',
    short: 'Add numbering',
    description: 'Add page numbers with position, size, and a starting number.',
    icon: Hash,
    category: 'edit',
    accent: 'cyan',
  },
  {
    id: 'watermark',
    name: 'Watermark',
    short: 'Stamp text',
    description: 'Add a tiled or single text watermark across every page.',
    icon: Sticker,
    category: 'edit',
    accent: 'emerald',
  },
  {
    id: 'images-to-pdf',
    name: 'Images to PDF',
    short: 'JPG/PNG → PDF',
    description: 'Convert one or many images into a single PDF document.',
    icon: FileImage,
    category: 'convert',
    accent: 'orange',
    multiple: true,
  },
  {
    id: 'pdf-to-images',
    name: 'PDF to Images',
    short: 'PDF → PNG',
    description: 'Render each page of a PDF to a high-resolution PNG image.',
    icon: Images,
    category: 'convert',
    accent: 'fuchsia',
  },
  {
    id: 'extract-text',
    name: 'Extract Text',
    short: 'PDF → text',
    description: 'Pull all readable text out of a PDF and copy or download it.',
    icon: FileText,
    category: 'convert',
    accent: 'lime',
  },
  {
    id: 'compress',
    name: 'Compress PDF',
    short: 'Reduce size',
    description: 'Rasterize pages to shrink file size with adjustable quality.',
    icon: Minimize2,
    category: 'optimize',
    accent: 'blue',
  },
  {
    id: 'info',
    name: 'PDF Info',
    short: 'Inspect metadata',
    description: 'See page count, dimensions, metadata, and file size of a PDF.',
    icon: Info,
    category: 'optimize',
    accent: 'slate',
  },
];

export const TOOL_MAP: Record<string, Tool> = Object.fromEntries(TOOLS.map((t) => [t.id, t]));

export const CATEGORIES: { id: Tool['category']; label: string }[] = [
  { id: 'organize', label: 'Organize' },
  { id: 'edit', label: 'Edit' },
  { id: 'convert', label: 'Convert' },
  { id: 'optimize', label: 'Optimize' },
];
